part of ai_awesome_message;

typedef void AwesomeMessageStatusCallback(AwesomeMessageStatus status);
typedef void OnTap(AwesomeMessage awesomeMessage);

/// A highly customizable widget so you can notify your user when you fell like he needs a beautiful explanation.
// ignore: must_be_immutable
class AwesomeMessage<T extends Object> extends StatefulWidget {
  AwesomeMessage(
      {Key? key,
      String? title,
      String? message,
      Widget? titleText,
      Widget? messageText,
      Widget? icon,
      bool? shouldIconPulse = true,
      double? maxWidth,
      EdgeInsets margin = const EdgeInsets.all(0.0),
      EdgeInsets padding = const EdgeInsets.all(16),
      double borderRadius = 0.0,
      Color? borderColor,
      double borderWidth = 1.0,
      Color backgroundColor = const Color(0xFF303030),
      Color? leftBarIndicatorColor,
      List<BoxShadow>? boxShadows,
      Gradient? backgroundGradient,
      TextButton? mainButton,
      OnTap? onTap,
      Duration? duration,
      bool isDismissible = true,
      AwesomeMessageDismissDirection dismissDirection = AwesomeMessageDismissDirection.VERTICAL,
      bool showProgressIndicator = false,
      AnimationController? progressIndicatorController,
      Color? progressIndicatorBackgroundColor,
      Animation<Color>? progressIndicatorValueColor,
      AwesomeMessagePosition awesomeMessagePosition = AwesomeMessagePosition.BOTTOM,
      AwesomeMessageStyle awesomeMessageStyle = AwesomeMessageStyle.FLOATING,
      Curve forwardAnimationCurve = Curves.easeOutCirc,
      Curve reverseAnimationCurve = Curves.easeOutCirc,
      Duration animationDuration = const Duration(seconds: 1),
      AwesomeMessageStatusCallback? onStatusChanged,
      double barBlur = 0.0,
      double overlayBlur = 0.0,
      Color overlayColor = Colors.transparent,
      Form? userInputForm})
      : this.title = title,
        this.message = message,
        this.titleText = titleText,
        this.messageText = messageText,
        this.icon = icon,
        this.shouldIconPulse = shouldIconPulse,
        this.maxWidth = maxWidth,
        this.margin = margin,
        this.padding = padding,
        this.borderRadius = borderRadius,
        this.borderColor = borderColor,
        this.borderWidth = borderWidth,
        this.backgroundColor = backgroundColor,
        this.leftBarIndicatorColor = leftBarIndicatorColor,
        this.boxShadows = boxShadows,
        this.backgroundGradient = backgroundGradient,
        this.mainButton = mainButton,
        this.onTap = onTap,
        this.duration = duration,
        this.isDismissible = isDismissible,
        this.dismissDirection = dismissDirection,
        this.showProgressIndicator = showProgressIndicator,
        this.progressIndicatorController = progressIndicatorController,
        this.progressIndicatorBackgroundColor = progressIndicatorBackgroundColor,
        this.progressIndicatorValueColor = progressIndicatorValueColor,
        this.awesomeMessagePosition = awesomeMessagePosition,
        this.awesomeMessageStyle = awesomeMessageStyle,
        this.forwardAnimationCurve = forwardAnimationCurve,
        this.reverseAnimationCurve = reverseAnimationCurve,
        this.animationDuration = animationDuration,
        this.barBlur = barBlur,
        this.overlayBlur = overlayBlur,
        this.overlayColor = overlayColor,
        this.userInputForm = userInputForm,
        super(key: key) {
    this.onStatusChanged = onStatusChanged ?? (status) {};
  }

  /// A callback for you to listen to the different AwesomeMessage status
  AwesomeMessageStatusCallback? onStatusChanged;

  /// The title displayed to the user
  final String? title;

  /// The message displayed to the user.
  final String? message;

  /// Replaces [title]. Although this accepts a [Widget], it is meant to receive [Text] or [RichText]
  final Widget? titleText;

  /// Replaces [message]. Although this accepts a [Widget], it is meant to receive [Text] or  [RichText]
  final Widget? messageText;

  /// Will be ignored if [backgroundGradient] is not null
  final Color? backgroundColor;

  /// If not null, shows a left vertical bar to better indicate the humor of the notification.
  /// It is not possible to use it with a [Form] and I do not recommend using it with [LinearProgressIndicator]
  final Color? leftBarIndicatorColor;

  /// [boxShadows] The shadows generated by AwesomeMessage. Leave it null if you don't want a shadow.
  /// You can use more than one if you feel the need.
  /// Check (this example)[https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/shadows.dart]
  final List<BoxShadow>? boxShadows;

  /// Makes [backgroundColor] be ignored.
  final Gradient? backgroundGradient;

  /// You can use any widget here, but I recommend [Icon] or [Image] as indication of what kind
  /// of message you are displaying. Other widgets may break the layout
  final Widget? icon;

  /// An option to animate the icon (if present). Defaults to true.
  final bool? shouldIconPulse;

  /// A [TextButton] widget if you need an action from the user.
  final TextButton? mainButton;

  /// A callback that registers the user's click anywhere. An alternative to [mainButton]
  final OnTap? onTap;

  /// How long until AwesomeMessage will hide itself (be dismissed). To make it indefinite, leave it null.
  final Duration? duration;

  /// True if you want to show a [LinearProgressIndicator].
  final bool showProgressIndicator;

  /// An optional [AnimationController] when you want to control the progress of your [LinearProgressIndicator].
  final AnimationController? progressIndicatorController;

  /// A [LinearProgressIndicator] configuration parameter.
  final Color? progressIndicatorBackgroundColor;

  /// A [LinearProgressIndicator] configuration parameter.
  final Animation<Color>? progressIndicatorValueColor;

  /// Determines if the user can swipe or click the overlay (if [overlayBlur] > 0) to dismiss.
  /// It is recommended that you set [duration] != null if this is false.
  /// If the user swipes to dismiss or clicks the overlay, no value will be returned.
  final bool? isDismissible;

  /// Used to limit AwesomeMessage width (usually on large screens)
  final double? maxWidth;

  /// Adds a custom margin to AwesomeMessage
  final EdgeInsets? margin;

  /// Adds a custom padding to AwesomeMessage
  /// The default follows material design guide line
  final EdgeInsets? padding;

  /// Adds a radius to all corners of AwesomeMessage. Best combined with [margin].
  /// I do not recommend using it with [showProgressIndicator] or [leftBarIndicatorColor].
  final double? borderRadius;

  /// Adds a border to every side of AwesomeMessage
  /// I do not recommend using it with [showProgressIndicator] or [leftBarIndicatorColor].
  final Color? borderColor;

  /// Changes the width of the border if [borderColor] is specified
  final double? borderWidth;

  /// AwesomeMessage can be based on [AwesomeMessagePosition.TOP] or on [AwesomeMessagePosition.BOTTOM] of your screen.
  /// [AwesomeMessagePosition.BOTTOM] is the default.
  final AwesomeMessagePosition awesomeMessagePosition;

  /// [AwesomeMessageDismissDirection.VERTICAL] by default.
  /// Can also be [AwesomeMessageDismissDirection.HORIZONTAL] in which case both left and right dismiss are allowed.
  final AwesomeMessageDismissDirection dismissDirection;

  /// AwesomeMessage can be floating or be grounded to the edge of the screen.
  /// If grounded, I do not recommend using [margin] or [borderRadius]. [AwesomeMessageStyle.FLOATING] is the default
  /// If grounded, I do not recommend using a [backgroundColor] with transparency or [barBlur]
  final AwesomeMessageStyle awesomeMessageStyle;

  /// The [Curve] animation used when show() is called. [Curves.easeOut] is default
  final Curve? forwardAnimationCurve;

  /// The [Curve] animation used when dismiss() is called. [Curves.fastOutSlowIn] is default
  final Curve? reverseAnimationCurve;

  /// Use it to speed up or slow down the animation duration
  final Duration? animationDuration;

  /// Default is 0.0. If different than 0.0, blurs only AwesomeMessage's background.
  /// To take effect, make sure your [backgroundColor] has some opacity.
  /// The greater the value, the greater the blur.
  final double? barBlur;

  /// Default is 0.0. If different than 0.0, creates a blurred
  /// overlay that prevents the user from interacting with the screen.
  /// The greater the value, the greater the blur.
  final double? overlayBlur;

  /// Default is [Colors.transparent]. Only takes effect if [overlayBlur] > 0.0.
  /// Make sure you use a color with transparency here e.g. Colors.grey[600].withOpacity(0.2).
  final Color? overlayColor;

  /// A [TextFormField] in case you want a simple user input. Every other widget is ignored if this is not null.
  final Form? userInputForm;

  AwesomeMessageRoute<T?>? _awesomeMessageRoute;

  /// Dismisses the AwesomeMessage causing is to return a future containing [result].
  /// When this future finishes, it is guaranteed that AwesomeMessage was dismissed.
  Future<T?> dismiss([T? result]) async {
    // If route was never initialized, do nothing
    if (_awesomeMessageRoute == null) {
      return null;
    }

    if (_awesomeMessageRoute!.isCurrent) {
      _awesomeMessageRoute?.navigator?.pop(result);
      return _awesomeMessageRoute?.completed;
    } else if (_awesomeMessageRoute!.isActive) {
      // removeRoute is called every time you dismiss a AwesomeMessage that is not the top route.
      // It will not animate back and listeners will not detect AwesomeMessageStatusStatus.IS_HIDING or AwesomeMessageStatusStatus.DISMISSED
      // To avoid this, always make sure that AwesomeMessage is the top route when it is being dismissed
      _awesomeMessageRoute?.navigator?.removeRoute(_awesomeMessageRoute!);
    }

    return null;
  }

  /// Checks if the AwesomeMessage is visible
  bool isShowing() {
    return _awesomeMessageRoute?.currentStatus == AwesomeMessageStatus.SHOWING;
  }

  /// Checks if the AwesomeMessage is dismissed
  bool isDismissed() {
    return _awesomeMessageRoute?.currentStatus == AwesomeMessageStatus.DISMISSED;
  }

  @override
  State createState() {
    return _AwesomeMessageState<T>();
  }
}

class _AwesomeMessageState<K extends Object> extends State<AwesomeMessage> with TickerProviderStateMixin {
  AwesomeMessageStatus? currentStatus;

  AnimationController? _fadeController;
  Animation<double>? _fadeAnimation;

  final Widget _emptyWidget = SizedBox(width: 0.0, height: 0.0);
  final double _initialOpacity = 1.0;
  final double _finalOpacity = 0.4;

  final Duration _pulseAnimationDuration = Duration(seconds: 1);

  late bool _isTitlePresent;
  late double _messageTopMargin;

  late FocusScopeNode _focusNode;
  late FocusAttachment _focusAttachment;

  @override
  void initState() {
    super.initState();

    assert(((widget.userInputForm != null || ((widget.message != null && widget.message!.isNotEmpty) || widget.messageText != null))), "A message is mandatory if you are not using userInputForm. Set either a message or messageText");

    _isTitlePresent = (widget.title != null || widget.titleText != null);
    _messageTopMargin = _isTitlePresent ? 6.0 : widget.padding!.top;

    _configureLeftBarFuture();
    _configureProgressIndicatorAnimation();

    if (widget.icon != null && widget.shouldIconPulse!) {
      _configurePulseAnimation();
      _fadeController?.forward();
    }

    _focusNode = FocusScopeNode();
    _focusAttachment = _focusNode.attach(context);
  }

  @override
  void dispose() {
    _fadeController?.dispose();

    widget.progressIndicatorController?.removeListener(_progressListener);
    widget.progressIndicatorController?.dispose();

    _focusAttachment.detach();
    _focusNode.dispose();
    super.dispose();
  }

  final Completer<Size> _boxHeightCompleter = Completer<Size>();

  void _configureLeftBarFuture() {
    SchedulerBinding.instance.addPostFrameCallback(
      (_) {
        final keyContext = backgroundBoxKey.currentContext;

        if (keyContext != null) {
          final RenderBox box = keyContext.findRenderObject() as RenderBox;
          _boxHeightCompleter.complete(box.size);
        }
      },
    );
  }

  void _configurePulseAnimation() {
    _fadeController = AnimationController(vsync: this, duration: _pulseAnimationDuration);
    _fadeAnimation = Tween(begin: _initialOpacity, end: _finalOpacity).animate(
      CurvedAnimation(
        parent: _fadeController!,
        curve: Curves.linear,
      ),
    );

    _fadeController?.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        _fadeController?.reverse();
      }
      if (status == AnimationStatus.dismissed) {
        _fadeController?.forward();
      }
    });

    _fadeController?.forward();
  }

  late VoidCallback _progressListener;

  void _configureProgressIndicatorAnimation() {
    if (widget.showProgressIndicator && widget.progressIndicatorController != null) {
      _progressListener = () {
        setState(() {});
      };
      widget.progressIndicatorController!.addListener(_progressListener);

      _progressAnimation = CurvedAnimation(curve: Curves.linear, parent: widget.progressIndicatorController!);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Align(
      heightFactor: 1.0,
      child: Material(
        color: widget.awesomeMessageStyle == AwesomeMessageStyle.FLOATING ? Colors.transparent : widget.backgroundColor,
        child: SafeArea(
          minimum: widget.awesomeMessagePosition == AwesomeMessagePosition.BOTTOM ? EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom) : EdgeInsets.only(top: MediaQuery.of(context).viewInsets.top),
          bottom: widget.awesomeMessagePosition == AwesomeMessagePosition.BOTTOM,
          top: widget.awesomeMessagePosition == AwesomeMessagePosition.TOP,
          left: false,
          right: false,
          child: _getAwesomeMessage(),
        ),
      ),
    );
  }

  Widget _getAwesomeMessage() {
    Widget awesomeMessage;

    if (widget.userInputForm != null) {
      awesomeMessage = _generateInputAwesomeMessage();
    } else {
      awesomeMessage = _generateAwesomeMessage();
    }

    return Stack(
      children: [
        FutureBuilder(
          future: _boxHeightCompleter.future,
          builder: (context, AsyncSnapshot<Size> snapshot) {
            if (snapshot.hasData) {
//              return ClipRect(
//                child: BackdropFilter(
//                  filter: ImageFilter.blur(
//                      sigmaX: widget.barBlur, sigmaY: widget.barBlur),
//                  child: Container(
//                    height: snapshot.data.height,
//                    width: snapshot.data.width,
//                    decoration: BoxDecoration(
//                      color: Colors.transparent,
//                      borderRadius: BorderRadius.circular(widget.borderRadius),
//                    ),
//                  ),
//                ),
//              );
              return ClipRRect(
                borderRadius: BorderRadius.circular(widget.borderRadius!),
                child: Container(
                  height: snapshot.data!.height,
                  width: snapshot.data!.width,
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    borderRadius: BorderRadius.circular(widget.borderRadius!),
                  ),
                ),
              );
            } else {
              return _emptyWidget;
            }
          },
        ),
        awesomeMessage,
      ],
    );
  }

  Widget _generateInputAwesomeMessage() {
    return Container(
      key: backgroundBoxKey,
      constraints: widget.maxWidth != null ? BoxConstraints(maxWidth: widget.maxWidth!) : null,
      decoration: BoxDecoration(
        color: widget.backgroundColor,
        gradient: widget.backgroundGradient,
        boxShadow: widget.boxShadows,
        borderRadius: BorderRadius.circular(widget.borderRadius!),
        border: widget.borderColor != null ? Border.all(color: widget.borderColor!, width: widget.borderWidth!) : null,
      ),
      child: Padding(
        padding: const EdgeInsets.only(left: 8.0, right: 8.0, bottom: 8.0, top: 16.0),
        child: FocusScope(
          child: widget.userInputForm!,
          node: _focusNode,
          autofocus: true,
        ),
      ),
    );
  }

  late CurvedAnimation _progressAnimation;
  GlobalKey backgroundBoxKey = GlobalKey();

  Widget _generateAwesomeMessage() {
    return Container(
      key: backgroundBoxKey,
      constraints: widget.maxWidth != null ? BoxConstraints(maxWidth: widget.maxWidth!) : null,
      decoration: BoxDecoration(
        color: widget.backgroundColor,
        gradient: widget.backgroundGradient,
        boxShadow: widget.boxShadows,
        borderRadius: BorderRadius.circular(widget.borderRadius!),
        border: widget.borderColor != null ? Border.all(color: widget.borderColor!, width: widget.borderWidth!) : null,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          widget.showProgressIndicator
              ? LinearProgressIndicator(
                  value: widget.progressIndicatorController != null ? _progressAnimation.value : null,
                  backgroundColor: widget.progressIndicatorBackgroundColor,
                  valueColor: widget.progressIndicatorValueColor,
                )
              : _emptyWidget,
          Row(
            mainAxisSize: MainAxisSize.max,
            children: _getAppropriateRowLayout(),
          ),
        ],
      ),
    );
  }

  List<Widget> _getAppropriateRowLayout() {
    double buttonRightPadding;
    double iconPadding = 0;
    if (widget.padding!.right - 12 < 0) {
      buttonRightPadding = 4;
    } else {
      buttonRightPadding = widget.padding!.right - 12;
    }

    if (widget.padding!.left > 16.0) {
      iconPadding = widget.padding!.left;
    }

    if (widget.icon == null && widget.mainButton == null) {
      return [
        _buildLeftBarIndicator(),
        Expanded(
          flex: 1,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              (_isTitlePresent)
                  ? Padding(
                      padding: EdgeInsets.only(
                        top: widget.padding!.top,
                        left: widget.padding!.left,
                        right: widget.padding!.right,
                      ),
                      child: _getTitleText(),
                    )
                  : _emptyWidget,
              Padding(
                padding: EdgeInsets.only(
                  top: _messageTopMargin,
                  left: widget.padding!.left,
                  right: widget.padding!.right,
                  bottom: widget.padding!.bottom,
                ),
                child: widget.messageText ?? _getDefaultNotificationText(),
              ),
            ],
          ),
        ),
      ];
    } else if (widget.icon != null && widget.mainButton == null) {
      return <Widget>[
        _buildLeftBarIndicator(),
        ConstrainedBox(
          constraints: BoxConstraints.tightFor(width: 42.0 + iconPadding),
          child: _getIcon(),
        ),
        Expanded(
          flex: 1,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              (_isTitlePresent)
                  ? Padding(
                      padding: EdgeInsets.only(
                        top: widget.padding!.top,
                        left: 4.0,
                        right: widget.padding!.left,
                      ),
                      child: _getTitleText(),
                    )
                  : _emptyWidget,
              Padding(
                padding: EdgeInsets.only(
                  top: _messageTopMargin,
                  left: 4.0,
                  right: widget.padding!.right,
                  bottom: widget.padding!.bottom,
                ),
                child: widget.messageText ?? _getDefaultNotificationText(),
              ),
            ],
          ),
        ),
      ];
    } else if (widget.icon == null && widget.mainButton != null) {
      return <Widget>[
        _buildLeftBarIndicator(),
        Expanded(
          flex: 1,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              (_isTitlePresent)
                  ? Padding(
                      padding: EdgeInsets.only(
                        top: widget.padding!.top,
                        left: widget.padding!.left,
                        right: widget.padding!.right,
                      ),
                      child: _getTitleText(),
                    )
                  : _emptyWidget,
              Padding(
                padding: EdgeInsets.only(
                  top: _messageTopMargin,
                  left: widget.padding!.left,
                  right: 8.0,
                  bottom: widget.padding!.bottom,
                ),
                child: widget.messageText ?? _getDefaultNotificationText(),
              ),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.only(right: buttonRightPadding),
          child: _getMainActionButton(),
        ),
      ];
    } else {
      return <Widget>[
        _buildLeftBarIndicator(),
        ConstrainedBox(
          constraints: BoxConstraints.tightFor(width: 42.0 + iconPadding),
          child: _getIcon(),
        ),
        Expanded(
          flex: 1,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              (_isTitlePresent)
                  ? Padding(
                      padding: EdgeInsets.only(
                        top: widget.padding!.top,
                        left: 4.0,
                        right: 8.0,
                      ),
                      child: _getTitleText(),
                    )
                  : _emptyWidget,
              Padding(
                padding: EdgeInsets.only(
                  top: _messageTopMargin,
                  left: 4.0,
                  right: 8.0,
                  bottom: widget.padding!.bottom,
                ),
                child: widget.messageText ?? _getDefaultNotificationText(),
              ),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.only(right: buttonRightPadding),
          child: _getMainActionButton() ?? _emptyWidget,
        )
      ];
    }
  }

  Widget _buildLeftBarIndicator() {
    if (widget.leftBarIndicatorColor != null) {
      return FutureBuilder(
        future: _boxHeightCompleter.future,
        builder: (BuildContext buildContext, AsyncSnapshot<Size> snapshot) {
          if (snapshot.hasData) {
            return Container(
              color: widget.leftBarIndicatorColor,
              width: 5.0,
              height: snapshot.data?.height,
            );
          } else {
            return _emptyWidget;
          }
        },
      );
    } else {
      return _emptyWidget;
    }
  }

  Widget _getIcon() {
    if (widget.icon != null && widget.icon is Icon && widget.shouldIconPulse!) {
      return FadeTransition(
        opacity: _fadeAnimation!,
        child: widget.icon,
      );
    } else if (widget.icon != null) {
      return widget.icon!;
    } else {
      return _emptyWidget;
    }
  }

  Widget _getTitleText() {
    return widget.titleText != null
        ? widget.titleText!
        : Text(
            widget.title ?? "",
            style: TextStyle(fontSize: 16.0, color: Colors.white, fontWeight: FontWeight.bold),
          );
  }

  Text _getDefaultNotificationText() {
    return Text(
      widget.message ?? "",
      style: TextStyle(fontSize: 14.0, color: Colors.white),
    );
  }

  TextButton? _getMainActionButton() {
    if (widget.mainButton != null) {
      return widget.mainButton!;
    } else {
      return null;
    }
  }
}
